# print ports and version
- block:
  - name: Check all Ports
    shell: ss -ntlp |awk '{print $4}'
    register: end_check_ports
    notify: end_check_ports
    
  - name: Display all versions
    shell: sudo sh -c "cat /data/logs/install_version.txt 2>/dev/null" || echo "no version information"
    register: end_check_versions
    notify: end_check_versions


- block:
  - name: Check Cloud
    shell : |
      if [ -f "/etc/waagent.conf" ];then echo "azure";fi
      if [ -d "/usr/local/aegis" ];then echo "alibabacloud";fi
      if [ -f "/snap/bin/amazon-ssm-agent.ssm-cli" ];then echo "aws";fi
      if [ -f "/usr/bin/amazon-ssm-agent" ];then echo "aws";fi
      if [ -d "/CloudrResetPwdAgent" ];then echo "huaiweicloud";fi
    register: cloud
    
  - debug:
      msg: "Cloud platform is {{cloud.stdout}}"
      
  # - name: Init for azure
  #   shell: |
  #     cloud-init clean
  #     waagent -deprovision+user --force
  #   when: cloud.stdout == 'azure'
    
  - name: Remove SSH info
    shell: sudo rm -rf {{item}}
    with_items:
      - /home/*/.ssh/*
      - /root/.ssh/*
      - /etc/ssh/ssh_host*
      
  - name: Install huawei agent
    shell: |
      chmod 400 /etc/ssh/*key
      chmod 400 /etc/ssh/*key.pub
      chattr +i /etc/ssh/*key
      chattr +i /etc/ssh/*key.pub
      echo "Ciphers aes256-ctr,aes192-ctr,aes128-ctr" >> /etc/ssh/sshd_config
      echo "MACs hmac-sha2-512,hmac-sha2-256" >> /etc/ssh/sshd_config
      sed -i 's/#HostbasedAuthentication no/HostbasedAuthentication no/g' /etc/ssh/sshd_config
      sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords no/g' /etc/ssh/sshd_config
      chown root:root /etc/ssh/sshd_config
      chmod og-rwx /etc/ssh/sshd_config
      chattr +i /etc/ssh/sshd_config
      chmod +x /root/HSSInstall
      /root/HSSInstall config
    when: cloud.stdout == 'huaiweicloud' 

  when: init == '1' or init == 1

# when ansible running as local, reboot can't use
- name: Reboot 
  reboot:
  when: init == '0' or init == 0
