- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars:
     app: "elastic"

- block:
  - pause:
      prompt: "Please login to Kibana UI and check it, then input Enter to continue"
      echo: no  
  - name: Output elk version
    shell: |
      echo "elk_version:" $(docker exec -i elastic-elasticsearch bin/elasticsearch --version | awk -F ' ' '{print $2}') |sudo tee -a /data/logs/install_version.txt
      sleep 20s
  - name: Delete contains and images resources
    shell: |
      docker compose down -v
      docker system prune --all --force
      docker network create websoft9
    args:
      chdir: /data/apps/elastic
