- pause:
    prompt: |
      Choice Odoo version: 
      0: Odoo16
      1: Odoo15
      2: Odoo14
      3: Odoo13
      4: Odoo12     
      private: no
      Default:0
  register: odoo_version_options

- set_fact:
    odoo_version_meta:
      "0": "16"
      "1": "15"
      "2": "14"
      "3": "13"
      "4": "12"
      
- set_fact:
    odoo_version: "{{odoo_version_meta[odoo_version_options.user_input]}}"

- debug:
    msg: "odoo_version is {{odoo_version}}"

- name: Config .env for start containers
  shell: |
    sed -i 's/APP_VERSION=.*/APP_VERSION={{odoo_version}}/g' {{installpath}}/{{appname}}/.env
