- pause:
    prompt: |
      Choice Erpnext version: 
      0: ERPNext14
      1: ERPNext13
      2: ERPNext12
      private: no
      Default:0
  register: erpnext_version_options

- set_fact:
    erpnext_version_meta:
      "0": "14"
      "1": "13"
      "2": "12"

- set_fact:
    erpnext_version: "{{erpnext_version_meta[erpnext_version_options.user_input]}}"

- debug:
    msg: "erpnext_version is {{erpnext_version}}"

- name: Config .env for start containers
  shell: |
    sed -i 's/APP_VERSION=.*/APP_VERSION=v{{erpnext_version}}/g' {{installpath}}/{{appname}}/.env
