- pause:
    prompt: |
      Choice Baota version: 
      0: Baota English version
      1: Baota Chinese version
      private: no
      Default:0
  register: baota_version_options

- set_fact:
    baota_version_meta:
      "0": "en"
      "1": "zh"

- set_fact:
    bt_language: "{{baota_version_meta[baota_version_options.user_input]}}"

- debug:
    msg: "bt_language is {{bt_language}}"
