- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars:
     app: "gitlab"

- block:
  - name: Delete jenkins  config
    shell: |
       cd /data/apps/jenkins && docker compose down -v
       rm -rf /data/apps/jenkins
  when: gitlab_version != "jenkins"
