- name: Install common on app without docker
  include_tasks: tasks/install_without_docker.yml
    
- name: Install {{appname}}
  shell: |
    wget http://repo.fastpanel.direct/install_fastpanel.sh -O - | bash - 

- name: Output version
  shell: echo "fastpanel version refer to https://fastpanel.direct/changelog" >> /data/logs/install_version.txt
