- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars:
     app: "onlyoffice"

- name: wait for {{appname}} start
  wait_for:
    port: "{{nginx_reverse_proxy_port}}"
    delay: 10
    timeout: 120
