- pause:
    prompt: |
      Choice Redis version: 
      0: Redis7.2
      1: Redis7.0
      2: Redis6.2
      3: Redis6.0
      4: Redis5.0
      5: Redis4.0
      6: Redis3.2
      7: Redis3.0
      8: Redis2.8
      private: no
      Default:0
  register: redis_version_options

- set_fact:
    redis_version_meta:
      "0": "7.2"
      "1": "7.0"
      "2": "6.2"
      "3": "6.0"
      "4": "5.0"
      "5": "4.0"
      "6": "3.2"
      "7": "3.0"
      "8": "2.8"
      
- set_fact:
    redis_version: "{{redis_version_meta[redis_version_options.user_input]}}"

- debug:
    msg: "redis_version is {{redis_version}}"

- name: Config .env for start containers
  shell: |
    sed -i 's/APP_VERSION=.*/APP_VERSION={{redis_version}}/g' {{installpath}}/{{appname}}/.env
