name: Create APPS from template

on:
  push:
    branches: [ main ]
    paths: 
      - 'apps/add'
jobs:
  build:
    name: Create apps
    runs-on: ubuntu-latest
    env:
      TAGS: latest
    steps:
      - uses: actions/checkout@master
      
      - name: Creating
        run: |
          cd apps && python3 create.py
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: new vendor
