name: Build and Publish File Packages

on:
  push:
    branches:
      - mainss

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build package
        run: |
          # Build your package here
          # For example, create a tar or zip file
          tar -czvf test.tar.gz ./tests

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MYGITHUB_ADMIN_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MYGITHUB_ADMIN_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test.tar.gz
          asset_name: test.tar.gz
          asset_content_type: application/gzip
