- name: Copy create_users.sh to /opt/
  template:
    src: create_users.sh
    dest: /opt/create_users.sh

- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars:
     app: "metabase"
     
- name: wait for {{appname}} start
  wait_for:
    port: "{{nginx_reverse_proxy_port}}"
    delay: 10
    timeout: 120
